### ISSUE TITLE
mirai+nonebot2，通过nb命令安装之后并不能完成转发功能

### ISSUE THREAD

**Issue by xianjiu-001** [ninthseason/nonebot_plugin_forwarder#4]
mirai+nonebot2，通过nb命令安装之后并不能完成转发功能，使用bot.send方法好像无响应

**Comment by ninthseason** [comment]
因为我未使用过mirai，对其并不了解。所以不能提供很好的帮助。

该插件是依赖于 onebot adapter 的：
`from nonebot.adapters.onebot.v11 import GroupMessageEvent, Bot`
调用的也是 onebot 的 `send_group_msg` API

我想是因为 mirai2 adapter 中没有这个 API 导致的问题吧。

**Comment by ninthseason** [comment]
此外请检查一下配置是否完整和正确：
```python
forwarder_source_group = ["<QQ群号>"]  # 源信息群
forwarder_dest_group = ["<QQ群号>"]  # 目标群
forwarder_prefix = ["<前缀格式>"]  # 触发转发的消息前缀 ( [""] 则为全部转发)
forwarder_explict = ["<QQ号>"]  # 指定只有特定人消息被转发 ( [""] 则为全部转发)
```

**Comment by xianjiu-001** [comment]
就是你所提到的mirai2 adapter中发送信息的api不一致导致的，在此之前我已经找到了解决方案。很高兴能得到你的回复与帮助，
