### ISSUE TITLE
也许是一个bug

### ISSUE THREAD

**Issue by metreone** [ninthseason/nonebot_plugin_forwarder#5]
在.env里这样写
![image](https://user-images.githubusercontent.com/100048167/188286352-206d5981-0e67-4169-bfb5-dd127c2eeb53.png)
bot就会复读并转发
![image](https://user-images.githubusercontent.com/100048167/188286384-7c3773e4-6940-4901-ab15-32cde9363fd9.png)
![image](https://user-images.githubusercontent.com/100048167/188286390-90daf20f-78c3-42e8-9b16-bbfd01e7eff0.png)
修复的话让bot不识别自己发送的消息就好了？

**Comment by metreone** [comment]
其实我就是想做个双向转发（小声）

**Comment by ninthseason** [comment]
确实是没考虑到的问题。今天会修复。

**Comment by ninthseason** [comment]
已更新。请更新插件（最新版本2.0.4）试试。

**Comment by metreone** [comment]
请问是否有想过给转发的消息加上一个发送人的群昵称？就像这样
![image](https://user-images.githubusercontent.com/100048167/188969950-4e82518e-2b9c-4c2f-b8b3-0f10235be2e6.png)

**Comment by metreone** [comment]
![image](https://user-images.githubusercontent.com/100048167/188970233-977d9a6a-fc7b-4c16-8908-5ef3a5babc2a.png)

**Comment by ninthseason** [comment]
暂不打算增添新的特性。
