### ISSUE TITLE
[enhancement]: 建议增加从环境变量读取配置

### ISSUE THREAD

**Issue by wei-z-git** [ninthseason/nonebot_plugin_forwarder#8]
建议增加从环境变量读取配置，便于在docker中运行

**Comment by SakuraPuare** [comment]
目前不就是从`.env`中读取配置吗？

**Comment by ninthseason** [comment]
我认为插件直接读取环境变量是徒增耦合。

不打算添加该功能。

但如果这种行为成为趋势，将考虑添加。
如果能举例几个有此功能的插件作为参考是最好的。

**Comment by wei-z-git** [comment]
Hello @ninthseason , 
Nonebot2 文档已经在推荐这种方式，大概是使用Pydantic来管理配置：
https://nb2.baka.icu/docs/tutorial/plugin/config-plugin

之前我参考（抄）的简易群管就是这样：
https://github.com/yzyyz1387/nonebot_plugin_admin/blob/main/nonebot_plugin_admin/config.py

主要俺的机器人是Docker部署，配置和应用程序需要分离，不然每次改配置**都需要重新build image**, 要疯

另外我顺手参考（抄）文档改了下，初步测试通过（居然可以用！），PR如下，供参考：
https://github.com/Utmost-Happiness-Planet/nonebot_plugin_forwarder/pull/9

**Comment by SakuraPuare** [comment]
通过修改容器的配置文件，可以在不 **rebuild image** 的情况下直接修改docker容器的 env ，如果嫌麻烦可以借助第三方 docker 管理工具，如 *portainer* 协助修改。

不是很清楚这样修改是如何将配置和程序分离的，鄙人认为都是通过 `get_driver().config` 接口访问Nonebot的配置，只是使用了Pydantic更加优雅，能否解释一下这是如何解决你的问题的。此外，如果我没记错，可以直接修改环境变量来修改程序配置。

既然官方文档已经在推荐这种方式配置读取方式，那也许应该修改本项目相关代码。

**Comment by ninthseason** [comment]
已合并，感谢贡献
